### ISSUE TITLE
Memory leak in native encode method

### ISSUE THREAD

**Issue by ayyybe** [Prior99/node-libpng#27]
Run the following code and inspect the node process's memory usage (`top -pid 1234`) and you'll see it's quickly eating up ram.
![](https://i.imgur.com/TYxtcwM.gif)
```js
const { encode } = require('node-libpng')

const imageData = Buffer.alloc(100 * 100 * 3);
const options = {
	width: 100,
	height: 100
};

console.log('pid:', process.pid)
setInterval(() => encode(imageData, options), 10)
```
The png write struct is never destroyed in the native encode method, resulting in a memory leak.

**Comment by Prior99** [comment]
Fixed in #28. Thanks!
