### ISSUE TITLE
Need support for Node v16

### ISSUE THREAD

**Issue by Mikuu** [Prior99/node-libpng#37]
Hello,

Thanks for the project, any plan to support Node v16, we need it.

**Comment by Prior99** [comment]
Hello. Yes I plan to support Node v16, however, I am currently unavailable
and not at the PC for a while. I'd be happy to review a pull request.

Am Di., 11. Mai 2021 um 10:12 Uhr schrieb Mikuu ***@***.***>:

**Comment by Prior99** [comment]
Support has been added in 0.2.20.

**Comment by Mikuu** [comment]
thanks
